/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.fausto.pfboxe.view.swing;

import br.edu.utfpr.fausto.pfboxe.modelo.rn.CategoriaRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.ClienteRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.SessaoRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.TreinadorRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.TreinamentoRN;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Categoria;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Cliente;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Sessao;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Treinador;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Treinamento;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoSessao;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoTreinador;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoTreinamento;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author f4ustx
 */
public class CadastrarTreinamento extends javax.swing.JInternalFrame {
    private Long idAlteracao = 0L;
    
    private Cliente cli;
    private ClienteRN clienteRN;
   
    private CategoriaRN categoriaRN;
    private Categoria categoria;
    private List<Categoria> categorias;

    private SessaoRN sessaoRN;
    private Sessao sessao;
    private List<Sessao> sessoes;
    
    private TreinamentoRN treinamentoRN;
    private Treinamento treinamento;
    private tipoTreinamento tipos;
    /**
     * Creates new form ConsultarTreinamento
     */
    public CadastrarTreinamento() {
        this.categoriaRN = new CategoriaRN();
        this.sessaoRN = new SessaoRN();
        this.sessao = new Sessao();
        this.categoria = new Categoria();
        this.treinamento=new Treinamento();
        this.treinamentoRN = new TreinamentoRN();
        this.cli = new Cliente();
        this.clienteRN = new ClienteRN();
        initComponents();
        FillBox();
    }
    
    public CadastrarTreinamento(Long idAlteracao){
        this.categoriaRN = new CategoriaRN();
        this.sessaoRN = new SessaoRN();
        this.sessao = new Sessao();
        this.categoria = new Categoria();
        this.treinamento=new Treinamento();
        this.treinamentoRN = new TreinamentoRN();
        this.cli = new Cliente();
        this.clienteRN = new ClienteRN();
        this.idAlteracao = idAlteracao;
        initComponents();
        FillBox();
        
        try{
            Treinamento t = treinamentoRN.listarUm(idAlteracao);
            cc.setText(t.getCliente().getCodigo().toString());
            desc.setText(t.getDesc());
            value.setText(String.valueOf(t.getValor()));
            
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    public void FillBox(){
        try{
            this.categorias  = categoriaRN.listaTodos();
            this.sessoes = sessaoRN.listaTodos();
            
            this.categorias.forEach((c) -> {
                ctg.addItem(c.getDescricao());
             });
            
            this.sessoes.forEach((s)->{
                ses.addItem(String.valueOf(s.getCodigo()));
            });
            
            tipo.setModel(new DefaultComboBoxModel<>(tipoTreinamento.values()));
        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        desc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        value = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ctg = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ses = new javax.swing.JComboBox<>();
        salvar = new javax.swing.JButton();
        cc = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cancelar1 = new javax.swing.JButton();
        pago = new javax.swing.JCheckBox();

        jLabel1.setText("Descrição:");

        desc.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Valor:");

        value.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel3.setText("Categoria:");

        jLabel4.setText("Tipo:");

        jLabel5.setText("Sessões:");

        salvar.setText("Salvar");
        salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarActionPerformed(evt);
            }
        });

        jLabel7.setText("Código (Cliente):");

        cancelar1.setText("Cancelar");
        cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelar1ActionPerformed(evt);
            }
        });

        pago.setText("Pago");
        pago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ctg, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ses, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(pago))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(salvar)
                        .addGap(75, 75, 75)
                        .addComponent(cancelar1)
                        .addGap(166, 166, 166))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelar1, salvar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(value, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(pago))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(ctg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(ses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar)
                    .addComponent(cancelar1))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarActionPerformed
        // TODO add your handling code here:
        try{
            if(idAlteracao == 0){
               sessao = sessaoRN.listarUm(Long.valueOf(ses.getSelectedItem().toString()));
               categoria = categoriaRN.listarDesc(ctg.getSelectedItem().toString());
               
               cli = clienteRN.listarUm(Long.valueOf(cc.getText()));
               
               treinamento.setCategoria(categoria);
               treinamento.setCliente(cli);
               treinamento.setSessao(sessao);
               treinamento.setValor(Float.parseFloat(value.getText()));
               treinamento.setPagamento(true);
               treinamento.setDesc(desc.getText());
               treinamento.setTipo(tipos.valueOf(tipo.getSelectedItem().toString()));
               treinamento.setPagamento(pago.isSelected());

               
               treinamentoRN.salvar(treinamento);
               JOptionPane.showMessageDialog(this, "Treinamento cadastrado!");

            }else{
               Treinamento t = treinamentoRN.listarUm(idAlteracao);
               sessao = sessaoRN.listarUm(Long.valueOf(ses.getSelectedItem().toString()));
               categoria = categoriaRN.listarDesc(ctg.getSelectedItem().toString());
               
               cli = clienteRN.listarUm(Long.valueOf(cc.getText()));
               
               t.setCategoria(categoria);
               t.setCliente(cli);
               t.setSessao(sessao);
               t.setValor(Float.parseFloat(value.getText()));
               t.setPagamento(true);
               t.setDesc(desc.getText());
               t.setTipo(tipos.valueOf(tipo.getSelectedItem().toString()));
               t.setPagamento(pago.isSelected());
               
               treinamentoRN.atualizar(t);
               JOptionPane.showMessageDialog(this, "Treinamento atualizado!");                
            }
        } catch(Exception e){
          JOptionPane.showMessageDialog(this, e);

        }
    }//GEN-LAST:event_salvarActionPerformed

    private void cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_cancelar1ActionPerformed

    private void pagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pagoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelar1;
    private javax.swing.JTextField cc;
    private javax.swing.JComboBox<String> ctg;
    private javax.swing.JTextField desc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox pago;
    private javax.swing.JButton salvar;
    private javax.swing.JComboBox<String> ses;
    private javax.swing.JComboBox<tipoTreinamento> tipo;
    private javax.swing.JTextField value;
    // End of variables declaration//GEN-END:variables
}
