/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.fausto.pfboxe.view.swing;

import br.edu.utfpr.fausto.pfboxe.modelo.rn.ClienteRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.TreinamentoRN;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Cliente;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Treinamento;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoPeso;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author f4ustx
 */
public final class CadastrarCliente extends javax.swing.JInternalFrame {

    private Long idAlteracao = 0L;
    private ClienteRN clienteRN;
    private TreinamentoRN treinamentoRN;
    private Cliente cli;
    private List<Treinamento> treinamentos;
    private Treinamento treinamento;
    private tipoPeso tipopeso;

    
    public CadastrarCliente() {
        this.clienteRN = new ClienteRN();
        this.treinamentoRN = new TreinamentoRN();
        this.treinamento = new Treinamento();
        this.cli = new Cliente();
        initComponents();
        FillBox();

    }
       
    public CadastrarCliente(Long idAlteracao) {
        this.clienteRN = new ClienteRN();
        this.cli = new Cliente();
        this.treinamentoRN = new TreinamentoRN();
        this.treinamento = new Treinamento();
        
        initComponents();
        FillBox();
        this.idAlteracao = idAlteracao;
        try{
            Cliente cliRecuperado = clienteRN.listarUm(idAlteracao);
            bolsa1.setText( String.valueOf(cliRecuperado.getBolsa()));
            nome.setText(cliRecuperado.getNome());
            cpf.setText(cliRecuperado.getCpf());
            tel.setText(cliRecuperado.getTelefone());
            sex.setText(cliRecuperado.getSexo());
            age.setText(String.valueOf(cliRecuperado.getIdade()));
           
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e);
        }
    }
    
    public void FillBox(){
        try{
            this.treinamentos  = treinamentoRN.listaTodos();
            this.treinamentos.forEach((t) -> {
                tr.addItem(t.getDesc());
             });
                        tipo.setModel(new DefaultComboBoxModel<>(tipoPeso.values()));

        } catch (Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        tr = new javax.swing.JComboBox<>();
        cadastrar = new javax.swing.JButton();
        tel = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bolsa1 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tipo = new javax.swing.JComboBox<>();
        sex = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        nome = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(615, 375));

        jLabel2.setText("Treinamento:");

        tr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trActionPerformed(evt);
            }
        });

        cadastrar.setText("Salvar");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        tel.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setText("Idade:");

        bolsa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        bolsa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bolsa1ActionPerformed(evt);
            }
        });

        jLabel9.setText("Sexo:");

        jLabel10.setText("Telefone:");

        jLabel11.setText("Bolsa:");

        jLabel12.setText("Peso:");

        sex.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        age.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        nome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeActionPerformed(evt);
            }
        });

        jLabel13.setText("Nome:");

        cpf.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel14.setText("CPF:");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tel))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(sex, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                            .addComponent(age)
                            .addComponent(cpf)
                            .addComponent(nome)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tipo, 0, 180, Short.MAX_VALUE)
                            .addComponent(bolsa1))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(64, 64, 64)
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(tr, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(cadastrar)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cancelar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cadastrar, cancelar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(tr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(cadastrar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelar))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(bolsa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void trActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
         try{
                if(this.idAlteracao == 0){
                    
                    treinamento = treinamentoRN.listarDesc(tr.getSelectedItem().toString());
                    treinamentos.add(treinamento);
                    
                    cli.setNome(nome.getText());
                    cli.setCpf(cpf.getText());
                    cli.setIdade(Integer.parseInt(age.getText()));
                    cli.setSexo(sex.getText());
                    cli.setBolsa(Float.parseFloat(bolsa1.getText()));
                    cli.setTelefone(tel.getText());
                    cli.setTipopeso(tipopeso.valueOf(tipo.getSelectedItem().toString()));
                    
                    cli.setTreinamentos(treinamentos);


                    this.clienteRN.salvar(cli);
                    JOptionPane.showMessageDialog(this, "Cliente cadastrado!");

                }else{
                    Cliente cliRecuperado = clienteRN.listarUm(idAlteracao);

                    cliRecuperado.setNome(this.nome.getText());

                    treinamento = treinamentoRN.listarDesc(tr.getSelectedItem().toString());
                    treinamentos.add(treinamento);
                    cli.setNome(nome.getText());
                    cli.setCpf(cpf.getText());
                    cli.setIdade(Integer.parseInt(age.getText()));
                    cli.setSexo(sex.getText());
                    cli.setBolsa(Float.parseFloat(bolsa1.getText()));
                    cli.setTelefone(tel.getText());
                    cli.setTipopeso(tipopeso.valueOf(tipo.getSelectedItem().toString()));
                    
                    clienteRN.atualizar(cliRecuperado);
                    JOptionPane.showMessageDialog(this, "Cliente atualizado!");

                }
            } catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }//GEN-LAST:event_cadastrarActionPerformed

    private void bolsa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bolsa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bolsa1ActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelarActionPerformed

    private void nomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JTextField bolsa1;
    private javax.swing.JButton cadastrar;
    private javax.swing.JButton cancelar;
    private javax.swing.JTextField cpf;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField sex;
    private javax.swing.JTextField tel;
    private javax.swing.JComboBox<tipoPeso> tipo;
    private javax.swing.JComboBox<String> tr;
    // End of variables declaration//GEN-END:variables
}
