/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.fausto.pfboxe.view.swing;

import br.edu.utfpr.fausto.pfboxe.modelo.rn.CategoriaRN;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Categoria;
import javax.swing.JOptionPane;

/**
 *
 * @author f4ustx
 */
public class CadastrarCategoria extends javax.swing.JInternalFrame {
    Long idAlteracao = 0L;
    
    Categoria categoria;
    CategoriaRN categoriaRN;
    /**
     * Creates new form CadastrarCategoria
     */
    public CadastrarCategoria() {
        this.categoriaRN = new CategoriaRN();
        this.categoria = new Categoria();
        initComponents();
    }
    
    public CadastrarCategoria(Long idAlteracao){
        this.categoriaRN = new CategoriaRN();
        this.categoria = new Categoria();
        initComponents();
        this.idAlteracao = idAlteracao;
        
        try{
            Categoria c = categoriaRN.listarUm(idAlteracao);
            
            min.setText(String.valueOf(c.getMin()));
            max.setText(String.valueOf(c.getMax()));
            descricao.setText(c.getDescricao());
            
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        min = new javax.swing.JTextField();
        max = new javax.swing.JTextField();
        descricao = new javax.swing.JTextField();
        btnCadastrar = new javax.swing.JButton();
        btnCadastrar1 = new javax.swing.JButton();

        jLabel1.setText("Mínimo:");

        jLabel2.setText("Máximo:");

        jLabel3.setText("Descrição:");

        min.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        max.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        descricao.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnCadastrar.setText("Salvar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnCadastrar1.setText("Cancelar");
        btnCadastrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastrar)
                        .addGap(31, 31, 31)
                        .addComponent(btnCadastrar1))
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCadastrar, btnCadastrar1});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCadastrar)
                    .addComponent(btnCadastrar1))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        // TODO add your handling code here:
        try{
            if(idAlteracao == 0){
                categoria.setDescricao(descricao.getText());
                categoria.setMin(Float.parseFloat(min.getText()));
                categoria.setMax(Float.parseFloat(max.getText()));
                
                categoriaRN.salvar(categoria);
                JOptionPane.showMessageDialog(this, "Categoria cadastrada com sucesso!");

            }else{
                Categoria c = categoriaRN.listarUm(idAlteracao);
                c.setDescricao(descricao.getText());
                c.setMin(Float.parseFloat(min.getText()));
                c.setMax(Float.parseFloat(max.getText()));
                
                categoriaRN.atualizar(c);
                JOptionPane.showMessageDialog(this, "Categoria atualizada com sucesso!");
            } 
        }catch(Exception e){
               JOptionPane.showMessageDialog(this, "Categoria não pode ser criada! Verifique as informações inseridas");
        }

    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnCadastrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrar1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnCadastrar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnCadastrar1;
    private javax.swing.JTextField descricao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField max;
    private javax.swing.JTextField min;
    // End of variables declaration//GEN-END:variables
}
