/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.utfpr.fausto.pfboxe.view.swing;

import br.edu.utfpr.fausto.pfboxe.modelo.dao.ConexaoHibernate;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.CategoriaRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.ClienteRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.SessaoRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.TreinadorRN;
import br.edu.utfpr.fausto.pfboxe.modelo.rn.TreinamentoRN;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Categoria;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Cliente;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Sessao;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Treinador;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.Treinamento;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoCliente;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoPeso;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoSessao;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoTreinador;
import br.edu.utfpr.fausto.pfboxe.modelo.vo.tipoTreinamento;
import java.util.ArrayList;
import java.util.List;
import javax.persistence.EntityManager;

/**
 *
 * @author f4ustx
 */
public class Principal extends javax.swing.JFrame {
    


    /**
     * Creates new form Principal
     */
    public Principal() {
                // Iniciar conexão com base de dados
        EntityManager manager = ConexaoHibernate.getInstance();
        initComponents();
        firstValues();

    }
    
    public void firstValues(){
        
                TreinadorRN treinadorRN = new TreinadorRN();
        Treinador treinador = new Treinador();
        Treinador treinador2 = new Treinador();
        List<Treinador> treinadores = new ArrayList<Treinador>();
        List<Sessao> sessoes = new ArrayList<Sessao>();

        TreinamentoRN treinamentoRN = new TreinamentoRN();
        Treinamento treinamento = new Treinamento();
        
        SessaoRN sessaoRN = new SessaoRN();
        Sessao sessao = new Sessao();
        
        CategoriaRN categoriaRN = new CategoriaRN();
        Categoria categoria = new Categoria();
                    
        treinador.setNome("John Nobody");
        treinador.setCpf("11122233344");
        treinador.setLicenca("EEF4531");
        treinador.setTelefone("1599998888");
        treinador.setSexo("Masculino");
        treinador.setTipo(tipoTreinador.PERSONAL);

        
        treinador2.setNome("Frank NoOne");
        treinador2.setCpf("11122233324");
        treinador2.setLicenca("IIG9134");
        treinador2.setTelefone("1599998848");
        treinador2.setSexo("Masculino");
        
        treinadores.add(treinador);
        
        categoria.setDescricao("Juvenil");
        categoria.setMax(18);
        categoria.setMin(14);
        categoria.setTreinadores(treinadores);
        treinador.setCategoria(categoria);
        treinador2.setCategoria(categoria);   
        treinador2.setTipo(tipoTreinador.FISIOTERAPEUTA);
       
        categoriaRN.salvar(categoria);

        treinadorRN.salvar(treinador);
        treinadorRN.salvar(treinador2);
        
        sessao.setPeso(tipoPeso.MEDIO);
        sessao.setTreinador(treinador);
        sessaoRN.salvar(sessao);
        sessoes.add(sessao);
        
        ClienteRN clienteRN = new ClienteRN();
        Cliente cliente = new Cliente();
        
        cliente.setNome("Maria marina");
        cliente.setCpf("11122233356");
        cliente.setBolsa(0);
        cliente.setTelefone("99998879");
        cliente.setSexo("Feminino");
        cliente.setIdade(20);
        cliente.setRanking(tipoCliente.INICIANTE);
        clienteRN.salvar(cliente);
        
        treinamento.setCategoria(categoria);
        treinamento.setCliente(cliente);
        treinamento.setDesc("Treinamento basico");
        treinamento.setTipo(tipoTreinamento.TECNICAS);
        treinamento.setValor(200);
        
        treinamentoRN.salvar(treinamento);
        sessao.setTreinamento(treinamento);
        sessaoRN.atualizar(sessao);

        System.out.println("Yes");

    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdpPrincipal = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        imCategoria = new javax.swing.JMenuItem();
        imCliente = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jdpPrincipal.setPreferredSize(new java.awt.Dimension(615, 375));

        javax.swing.GroupLayout jdpPrincipalLayout = new javax.swing.GroupLayout(jdpPrincipal);
        jdpPrincipal.setLayout(jdpPrincipalLayout);
        jdpPrincipalLayout.setHorizontalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );
        jdpPrincipalLayout.setVerticalGroup(
            jdpPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        jMenu1.setText("Cadastro");

        imCategoria.setText("Categoria");
        imCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imCategoriaActionPerformed(evt);
            }
        });
        jMenu1.add(imCategoria);

        imCliente.setText("Cliente");
        imCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imClienteActionPerformed(evt);
            }
        });
        jMenu1.add(imCliente);

        jMenuItem4.setText("Treinador");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Treinamento");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Ajuda");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jdpPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void imCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imCategoriaActionPerformed
        // TODO add your handling code here:
        ConsultarCategoria consultaCategoria = new ConsultarCategoria(jdpPrincipal);
        this.jdpPrincipal.add(consultaCategoria);
        consultaCategoria.setVisible(true);
        
    }//GEN-LAST:event_imCategoriaActionPerformed

    private void imClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imClienteActionPerformed
        // TODO add your handling code here:
        ConsultarCliente consultaCliente = new ConsultarCliente(jdpPrincipal);
        this.jdpPrincipal.add(consultaCliente);
        consultaCliente.setVisible(true);
    }//GEN-LAST:event_imClienteActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        ConsultarTreinador consultaTreinador = new ConsultarTreinador(jdpPrincipal);
        this.jdpPrincipal.add(consultaTreinador);
        consultaTreinador.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        ConsultarTreinamento consultaTreinamento = new ConsultarTreinamento(jdpPrincipal);
        this.jdpPrincipal.add(consultaTreinamento);
        consultaTreinamento.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem imCategoria;
    private javax.swing.JMenuItem imCliente;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JDesktopPane jdpPrincipal;
    // End of variables declaration//GEN-END:variables
}
